# Don't allow new windows to be larger than the screen.
autofit-larger=50%x50%
# Enable hardware decoding if available, =yes is implied.
hwdec=auto
vo=gpu
# gpu-api=vulkan
hwdec-codecs=all
# Spaces don't have to be escaped.
osd-playing-msg=File: ${filename}
# Seek issue fix
Right seek 5 exact
Left seek -5 exact
# TEST back seek audio sync issue fix
hr-seex=always
