[general]
import = ["themes/hyper.toml",]
working_directory = "~"
live_config_reload = true
ipc_socket = false

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = true
decorations = "None" # "Full" | "None" | "Transparent" | "Buttonless"
opacity = 1.0
blur = false
startup_mode = "Windowed" # "Windowed" | "Maximized" | "Fullscreen" | "SimpleFullscreen"
title = "Alacritty"
dynamic_title = false
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "Dark" # "Dark" | "Light" | "None"
resize_increments = false
level = "Normal" # "Normal" | "AlwaysOnTop"

[scrolling]
history = 10000
multiplier = 3 # How much to scroll

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { style = "Bold" }
italic = { style = "Italic" }
bold_italic = { style = "Bold Italic" }
size = 10
offset = { x = 0, y = 0 }
builtin_box_drawing = true

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 500
blink_timeout = 0
unfocused_hollow = true
thickness = 0.15
